# Internal role variables and values that must NOT be overridden by the user.
#
# Variables defined here usually dropin earlier definitions due to the high
# precedence of this file. Each variable should have a concise comment above
# it, describing its purpose and how it fits into the role's functionality.

---

# List of facts used by the role (gathered on a best-effort basis if needed).
#
# To identify which subset a fact belongs to during development, you can use
# the following snippet:
#
# - ansible.builtin.setup:
#     gather_subset:
#       - '!min'
#       - '<subset_name, see parameter doc for details>'
__run_logrotate_used_facts:
  # from subset "distribution"
  - "distribution"
  - "distribution_major_version"
  - "distribution_version"
  - "os_family"


# List of platforms this role supports and was designed for.
#
# A warning will be issued if the list contains values and the role is executed
# on an unknown (not listed) platform, but execution will continue. Example:
#
# - name: "Fedora" # A ansible_facts value ('distribution' or 'os_family')
#   versions: # A ansible_facts value ('distribution_major_version' or
#     - "all" # 'distribution_version') or "all"
# - name: "Ubuntu"
#   versions:
#     - "22.04"
#     - "24.04"
# - name: "RedHat"
#   versions:
#     - "all"
# - name: "Debian"
#   versions:
#     - "all"
__run_logrotate_supported_platforms: []


# List of package names to be installed when run_logrotate_state is
# set to "present".
__run_logrotate_packages_install:
  - "logrotate"


# List of package names to be uninstalled when run_logrotate_state is
# set to "absent". This variable is useful when __run_logrotate_packages_install
# contains packages that are required for the managed software to function but
# should not be removed during uninstallation, as doing so could break other
# software. This is usually the case if there are common dependencies like
# "curl" or "openssl" which typically should remain installed even after
# uninstalling the software managed by this role.
__run_logrotate_packages_uninstall: "{{ run_logrotate_packages_install }}"


# List of package names to be removed unconditionally before installation
# (e.g., to prevent conflicts or resolve incompatibilities).
__run_logrotate_packages_removal: []


# List of paths of files and directories to be removed unconditionally after
# installation. This is useful for removing default configuration resources
# that would otherwise create confusion or conflict with custom configurations
# managed by this role.
__run_logrotate_paths_removal: []


# Configuration file paths, ownership, and permissions. These variables define
# the different locations of configuration files, include directories, and
# Ansible-managed files, ensuring consistent file handling across distributions.
__run_logrotate_config_file_path: "/etc/logrotate.conf"
__run_logrotate_config_file_owner: "root"
__run_logrotate_config_file_group: "root"
__run_logrotate_config_file_mode: "u=rw,g=r,o=r" # 0644

__run_logrotate_config_dropin_dir_path: "/etc/logrotate.d"
__run_logrotate_config_dropin_dir_owner: "{{ __run_logrotate_config_file_owner }}"
__run_logrotate_config_dropin_dir_group: "{{ __run_logrotate_config_file_group }}"
__run_logrotate_config_dropin_dir_mode: "u=rwx,g=rx,o=rx" # 0755

__run_logrotate_config_dropin_file_owner: "{{ __run_logrotate_config_file_owner }}"
__run_logrotate_config_dropin_file_group: "{{ __run_logrotate_config_file_group }}"
__run_logrotate_config_dropin_file_mode: "{{ __run_logrotate_config_file_mode }}"

__run_logrotate_config_defaults_dropin_file_path: "{{ __run_logrotate_config_dropin_dir_path }}/{{ run_logrotate_config_defaults_dropin_file_name }}"
__run_logrotate_config_defaults_dropin_file_path_default: "{{ __run_logrotate_config_dropin_dir_path }}/00-defaults" # needed to detect non-default names


# Paths of executables for management and validation.
__run_logrotate_logrotate_exec_path: "/usr/sbin/logrotate"


# systemd logrotate timer (helpful: systemctl cat logrotate.timer)
__run_logrotate_systemd_timer_unit_name: "logrotate.timer"
__run_logrotate_systemd_timer_unit_file_path: "/usr/lib/systemd/system/logrotate.timer" # hint to determine the path: systemctl cat logrotate.timer

__run_logrotate_systemd_timer_unit_dropin_dir_path: "/etc/systemd/system/{{ __run_logrotate_systemd_timer_unit_name }}.d/"
__run_logrotate_systemd_timer_unit_dropin_dir_owner: "{{ __run_logrotate_config_file_owner }}"
__run_logrotate_systemd_timer_unit_dropin_dir_group: "{{ __run_logrotate_config_file_group }}"
__run_logrotate_systemd_timer_unit_dropin_dir_mode: "{{ __run_logrotate_config_dropin_dir_mode }}"

__run_logrotate_systemd_timer_unit_dropin_file_path: "{{ __run_logrotate_systemd_timer_unit_dropin_dir_path }}/dropin.conf"
__run_logrotate_systemd_timer_unit_dropin_file_owner: "{{ __run_logrotate_config_file_owner }}"
__run_logrotate_systemd_timer_unit_dropin_file_group: "{{ __run_logrotate_config_file_group }}"
__run_logrotate_systemd_timer_unit_dropin_file_mode: "{{ __run_logrotate_config_file_mode }}"


### Override defaults of dependencies used by this role (if any).

# nothing right now
