# Internal role variables specific to: Ubuntu 22.04 LTS (Jammy Jellyfish)
#
# Only values specific to the platform and its functionality should be included
# here. Variables in this file override those defined in vars/main.yml.
#
# Each variable should have a concise comment above it, describing its purpose
# and how it fits into the role's functionality.

---

__run_logrotate_systemd_timer_unit_file_path: "/lib/systemd/system/logrotate.timer" # hint to determine the path: systemctl cat logrotate.timer
