# Configuration: Manage settings, like adapting or creating config files.

---

- name: "Config | Default | Ensure main config file exists with proper permissions"
  ansible.builtin.file:
    path: "{{ __run_logrotate_config_file_path }}"
    state: "touch"
    owner: "{{ __run_logrotate_config_file_owner }}"
    group: "{{ __run_logrotate_config_file_group }}"
    mode: "{{ __run_logrotate_config_file_mode }}"
    access_time: "preserve"
    modification_time: "preserve"


- name: "Config | Default | Ensure drop-in config directory exists with proper permissions"
  ansible.builtin.file:
    path: "{{ __run_logrotate_config_dropin_dir_path }}"
    state: "directory"
    owner: "{{ __run_logrotate_config_dropin_dir_owner }}"
    group: "{{ __run_logrotate_config_dropin_dir_group }}"
    mode: "{{ __run_logrotate_config_dropin_dir_mode }}"
  notify:
    - "run_logrotate: validate configuration"

## Defaults drop-in

- name: "Config | Default | Create drop-in config file (logrotate defaults)"
  ansible.builtin.template:
    src: "logrotate_defaults.conf.j2"
    dest: "{{ __run_logrotate_config_defaults_dropin_file_path }}"
    owner: "{{ __run_logrotate_config_dropin_file_owner }}"
    group: "{{ __run_logrotate_config_dropin_file_group }}"
    mode: "{{ __run_logrotate_config_dropin_file_mode }}"
  vars:
    # Pass (and/or adjust) variables needed for the template
    tpl_defaults_conf: "{{ run_logrotate_config_defaults }}"
  notify:
    - "run_logrotate: validate configuration"


- name: "Config | Default | Remove role's default drop-in config file (logrotate defaults) (if custom filename is used)"
  ansible.builtin.file:
    path: "{{ __run_logrotate_config_defaults_dropin_file_path_default }}"
    state: "absent"
  when:
    - __run_logrotate_config_defaults_dropin_file_path != __run_logrotate_config_defaults_dropin_file_path_default
  notify:
    - "run_logrotate: validate configuration"


## User define app-specific sections, additional drop-in files

- name: "Config | Default | Create drop-in config files"
  ansible.builtin.template:
    src: "logrotate_section.conf.j2"
    dest: "{{ __run_logrotate_config_dropin_dir_path }}/{{ __run_logrotate_loop_file_name }}"
    owner: "{{ __run_logrotate_config_dropin_file_owner }}"
    group: "{{ __run_logrotate_config_dropin_file_group }}"
    mode: "{{ __run_logrotate_config_dropin_file_mode }}"
  vars:
    __run_logrotate_loop_file_name: >-
      {{
        item['key']
        | ansible.builtin.lower
        | ansible.builtin.regex_replace('[^a-z0-9._]', '_')
        | ansible.builtin.regex_replace('_+', '_')
        | ansible.builtin.regex_replace('^_|_$', '')
      }}
    # Pass (and/or adjust) variables needed for the template
    tpl_section_conf: "{{ item['value'] }}"
  loop: >-
    {{
      run_logrotate_config_sections
      | ansible.builtin.default({})
      | ansible.builtin.dict2items
    }}
  loop_control:
    label: "{{ __run_logrotate_config_dropin_dir_path }}/{{ __run_logrotate_loop_file_name }}"
  when:
    - ((run_logrotate_config_sections | ansible.builtin.default({})) | ansible.builtin.length) > 0
  notify:
    - "run_logrotate: validate configuration"


- name: "Config | Default | Ensure 'Include' directive exists in main service config file"
  ansible.builtin.lineinfile:
    path: "{{ __run_logrotate_config_file_path }}"
    line: "include {{ __run_logrotate_config_dropin_dir_path }}"
    state: "present"
  notify:
    - "run_logrotate: validate configuration"
