# Uninstall: Manage basic resource removal, such as packages or service users.

---

# Fixed paths cover files written by releases without the ownership marker.
- name: "Setup | Uninstall | Remove drop-in config files (defaults, systemd timer)"
  ansible.builtin.file:
    path: "{{ __run_logrotate_dropin_path_item }}"
    state: absent
  loop: >-
    {{
      [
        __run_logrotate_config_defaults_dropin_file_path,
        __run_logrotate_config_defaults_dropin_file_path_default,
        __run_logrotate_systemd_timer_unit_dropin_file_path
      ] | ansible.builtin.unique
    }}
  loop_control:
    loop_var: "__run_logrotate_dropin_path_item"


- name: "Setup | Uninstall | Find files in the drop-in config directory"
  ansible.builtin.find:
    paths:
      - "{{ __run_logrotate_config_dropin_dir_path }}"
    file_type: "file"
    hidden: true
  register: __run_logrotate_find_result


- name: "Setup | Uninstall | Determine files created by this role (ownership marker)"
  ansible.builtin.command:
    argv: >-
      {{
        [__run_logrotate_grep_exec_path, '-l', '-s', '-x', '-F', '--', __run_logrotate_config_file_marker]
        + (__run_logrotate_find_result['files'] | ansible.builtin.map(attribute='path') | ansible.builtin.list)
      }}
  register: __run_logrotate_owned_result
  changed_when: false
  failed_when:
    - __run_logrotate_owned_result['rc'] not in [0, 1, 2]
  when:
    - (__run_logrotate_find_result['files'] | ansible.builtin.length) > 0


- name: "Setup | Uninstall | Remove files created by this role"
  ansible.builtin.file:
    path: "{{ __run_logrotate_created_path_item }}"
    state: "absent"
  loop: "{{ __run_logrotate_owned_result['stdout_lines'] | ansible.builtin.default([]) }}"
  loop_control:
    loop_var: "__run_logrotate_created_path_item"


- name: "Setup | Uninstall | Remove packages"
  ansible.builtin.package:
    name: "{{ __run_logrotate_packages_uninstall }}"
    state: "absent"
  when:
    - __run_logrotate_packages_uninstall is ansible.builtin.defined
    - (__run_logrotate_packages_uninstall | ansible.builtin.length) > 0
